name: Deploy Frontend to K8S
on:
  push:
    paths:
      - 'frontend/index.html'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.0'

      - name: Apply ConfigMap to K8S
        working-directory: ./frontend
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl create configmap frontend-html \
            --from-file=index.html \
            -o yaml --dry-run=client | kubectl apply -f -
          kubectl rollout restart deployment frontend